name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHC
        uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.3"

      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build and run tests
        run: "stack test --fast --no-terminal --system-ghc"
